/*
* Autor: Pedro Lopez
* Fecha: 06-10-2022
* Version: 1.0
* Contenido: Creación de la base de datos
*/

CREATE DATABASE IF NOT EXISTS ALMACEN_ALLEN CHARSET UTF8MB4 COLLATE UTF8MB4_SPANISH2_CI;
USE ALMACEN_ALLEN;