/*
* Autor: Pedro Lopez & Benjamín Galarce
* Fecha: 06-10-2022
* Version: 2.0
* Contenido: Creación de las tablas de la base de datos
*/

-- -----------------------------------------------------
-- TABLA PROVEEDOR
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS PROVEEDOR (
  IDPROVEEDOR INT NOT NULL AUTO_INCREMENT,
  NOMBREPROVEEDOR VARCHAR(50) NOT NULL,
  RUTPROVEEDOR VARCHAR(12) NOT NULL,
  TELEFONOPROVEEDOR VARCHAR(12) NOT NULL,
  CONTACTOPROVEEDOR VARCHAR(50) NOT NULL,
  DIRECCIONPROVEEDOR VARCHAR(50) NOT NULL,
  PRIMARY KEY (IDPROVEEDOR));

-- -----------------------------------------------------
-- TABLA PRODUCTOS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS PRODUCTOS (
  CODIGOPRODUCTO VARCHAR(30) NOT NULL,
  DESCRIPCIONPRODUCTO VARCHAR(100) NOT NULL,
  CANTIDADPRODUCTO INT NOT NULL,
  VALORPRODUCTO INT NOT NULL,
  IDPROVEEDOR INT,
  PRIMARY KEY (CODIGOPRODUCTO),
    FOREIGN KEY (IDPROVEEDOR)
    REFERENCES PROVEEDOR (IDPROVEEDOR));

-- -----------------------------------------------------
-- TABLA ESTADOPRODUCTO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ESTADOPRODUCTO (
  ESTADOPRODUCTOID INT NOT NULL,
  ESTADOPRODUCTODESCRIPCION VARCHAR(30) NULL,
    PRIMARY KEY (ESTADOPRODUCTOID));

-- -----------------------------------------------------
-- TABLA INVENTARIO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS INVENTARIO (
  CODIGOINVENTARIO VARCHAR(30) NOT NULL,
  INVENTARIOFECHA DATE NOT NULL,
  INVENTARIOSTOCK INT NOT NULL,
  CODIGOPRODUCTO VARCHAR(30),
  ESTADOPRODUCTOID INT,
    FOREIGN KEY (CODIGOPRODUCTO)
    REFERENCES PRODUCTOS (CODIGOPRODUCTO),
    FOREIGN KEY (ESTADOPRODUCTOID)
    REFERENCES ESTADOPRODUCTO (ESTADOPRODUCTOID));