/*
* Autor: Benjamín Galarce
* Fecha: 08-10-2022
* Version: 1.0
* Nombre: sp_actualizarproductos
*
* Parámetros:
*	_CODIGOPRODUCTO: código verificador del producto.
*	_DESCRIPCIONPRODUCTO: nombre del producto
*	_CANTIDADPRODUCTO: cantidad(stock) del producto
*	_VALORPRODUCTO: precio del producto
*/

-- --------------------------------------------------------
-- PROCEDIMIENTO ALMACENADO ACTUALIZAR 5 PRODUCTOS
-- --------------------------------------------------------

delimiter $$
create procedure SP_ACTUALIZARPRODUCTOS(
	IN _CODIGOPRODUCTO VARCHAR(30),
    IN _DESCRIPCIONPRODUCTO VARCHAR(100),
    IN _CANTIDADPRODUCTO INT,
    IN _VALORPRODUCTO INT
)
begin
	UPDATE PRODUCTOS
    SET DESCRIPCIONPRODUCTO = _DESCRIPCIONPRODUCTO, CANTIDADPRODUCTO = _CANTIDADPRODUCTO,
    VALORPRODUCTO = _VALORPRODUCTO
    WHERE CODIGOPRODUCTO = _CODIGOPRODUCTO;
end;
$$

CALL SP_ACTUALIZARPRODUCTOS ("10000000000001", "NESCAFÉ CAPPUCCINO VAINILLA", "25", "4000");
CALL SP_ACTUALIZARPRODUCTOS ("20000000000002", "GALLETAS SALVADO", "15", "2000");
CALL SP_ACTUALIZARPRODUCTOS ("30000000000003", "JUGO", "15", "1000");
CALL SP_ACTUALIZARPRODUCTOS ("40000000000002", "GALLETAS CARIOCA CHOCOLATE", "10", "1000");
CALL SP_ACTUALIZARPRODUCTOS ("50000000000001", "RAMITAS", "25", "1800");